### PR TITLE
Add port parameter to local command

### PR DESCRIPTION
**Pull request by gliptak**
Please check closely as my local dev environment is not fully running ...

### CODE REVIEW

**Comment by dondoco7** [comment]
+1

**Comment by andriisoldatenko** [comment]
@gliptak Can you please add unit tests?
`will decrease coverage by 0.14%`

**Comment by gliptak** [comment]
@andriisoldatenko Would you offer a recommendation which unit test to ```clone``` from? Thanks

**Comment by gliptak** [comment]
Any guidance? Thanks

**Comment by jamesls** [comment]
Thanks for the pull request and sorry for the delay.  I've gone ahead and added a test so we can get this merged.

**Pull request merged**
