### PR TITLE
Environment Variable and VPC Support

### PR DESCRIPTION
**Pull request by emellis**
Adds support for lambda environment variables to chalice.

### CODE REVIEW

**Comment by emellis** [comment]
Added additional support for VPC configuration and clarified some tests and docs.

**Comment by stan-sack** [comment]
Would love to see this feature

**Comment by jamesls** [comment]
Hi, thanks for the pull request.  Environment variables and VPC support are things I'd like to support in chalice.  I'm in the process of refactoring the internals to make these types of changes easier in the future.  I'll get this PR rebased against the latest changes in master.

**Comment by emellis** [comment]
Yeah, it looks like the swagger based API gateway config (which I love by the way, excited for SAM support) conflicts with this a bit. I'll take a look at it tomorrow as well and see what all needs to be updated.

**Comment by emellis** [comment]
This PR now has the latest changes in master merged into it.

**Comment by emellis** [comment]
This work has been continued in PR 273

**Pull request closed without merging**
