### PR TITLE
allow using a pre-configured IAM role 

### PR DESCRIPTION
**Pull request by sdole**
see issue #61. This is my proposal to fix it.

### CODE REVIEW

**Comment by jamesls** [comment]
Sorry for the delay, I've been OOTO until today.

Overall, I think this change looks good.  I do have one question.  In considering additional features such as https://github.com/awslabs/chalice/issues/40 where I'd like to track everything I create so that I can subsequently delete them in a `chalice delete` command, I'm thinking about writing to disk every thing I create, possibly in the `config.json`.  If that's the case, it might help if the config was more explicit about whether or not to create a role and autogenerate a policy.  What do you think about something like this:

```
{"role_arn": "arn:....", "manage_role": false}
 ```

Not really sure what to call the config option, but some sort of boolean config option that explicitly says "don't touch the role_arn".

What do you think?

**Comment by sdole** [comment]
good idea! done. also, changed the config keys to iam_role_arn and manage_iam_role so that it is clear we are talking about iam roles. thanks!

**Comment by sdole** [comment]
Hello, Let me know if you want me to make any changes. I am fairly new to python, so, don't hesitate to comment on my code - i will learn something. thanks.

**Comment by sdole** [comment]
this build seems to have failed due to some documentation changes unrelated to this pull request.

**Comment by jamesls** [comment]
Thanks.  Would you mind squashing your commits and rebasing against master?  That should fix the doc errors you're seeing.

**Comment by sdole** [comment]
squashing and rebase was getting complicated. I just re-did a new fork, manually applied changes and requested a new pull #85. Closing this.

**Pull request closed without merging**
