### PR TITLE
Issues-20: add lambda alias support

### PR DESCRIPTION
**Pull request by b-b3rn4rd**
As discussed in https://github.com/awslabs/chalice/issues/20, summary of lambda stage feature:
- Each lambda is published after deployment
- Lambda stage alias is updated to the latest published version
- Api gateway stage is pointing to the related lambda alias

Example:
App.py
app
Initial deployment to `dev` stage
dev-initial
Checking `dev` stage response
dev-web
Initial deployment to `prod`
prod-initial
Checking `prod` api
prod-web

Changing code
app-code-change
Making new deployment to `dev` stage
dev-new-stage
Verifying `dev` stage changes
dev-new-version-web

Guys, I look forward to get your opinion.

P.S. Regarding different stages and multiple accounts, I reckon this is more related to AWS STS, and could be done transparently to the framework. For instance you could  allow dev account to assume prod account role to manage api gateway/lambda and before deployment to prod environment  assume that role

### CODE REVIEW

**Comment by b-b3rn4rd** [comment]
don't worry about failign unittest I'll fix it if PR looks promising

**Comment by andriisoldatenko** [comment]
@b-b3rn4rd  Can you please rebase from master to resolve conflicts?

**Comment by jamesls** [comment]
Closing out old pull request.  https://github.com/awslabs/chalice/issues/20 has been resolved, and we ended up creating a completely separate set of resources per stage in order to accommodate other AWS resources outside of API gateway and lambda.

**Comment by KeynesYouDigIt** [comment]
Was support for lambda aliases ever added? I would like to add an explicit alias to a lambda in my app so I can reliably invoke it elsewhere.

**Pull request closed without merging**
