### PR TITLE
require pep257 for dev users

### PR DESCRIPTION
**Pull request by JamieCressey**

### CODE REVIEW

**Comment by r3d4rmy** [comment]
pep257 has been [renamed](https://github.com/PyCQA/pydocstyle/issues/172) to pydocstyle

**Comment by JamieCressey** [comment]
Thanks @r3d4rmy, updated.

**Comment by jamesls** [comment]
Thanks for the pull request, sorry for the delay, I've been OOTO for the last couple weeks.

**Comment by jamesls** [comment]
Merged in 9f6c9b6a97f099d09b99710763ba38e651002fb1

**Pull request closed without merging**
