### PR TITLE
Content type lookup with lowercased key

### PR DESCRIPTION
**Pull request by hadrien**
To address issue #129

### CODE REVIEW

**Comment by chrisgilmerproj** [comment]
This looks great.  Thanks for the quick turnaround on it.

**Comment by chrisgilmerproj** [comment]
@hadrien - any chance this will get added and released this week?  I don't mean to pressure I'd just like to fix my app so I can deploy it.

**Comment by hadrien** [comment]
@chrisgilmerproj I am not a part of aws so I cannot give you any detail, I do not have merging permission: Actually, I need that fix too :-)

@jamesls Whenever you have the time to give feedback, it will be super appreciated, thanks!

**Comment by chrisgilmerproj** [comment]
Oh! Interesting.  Well I appreciate the work @hadrien - thank you very much for your time on this.  It's going to be a big help for me and I hope others as well.

**Comment by jamesls** [comment]
Thanks for the pull request.  In general I think this is a good change to add, the only problem I see is that this line:

```
self.headers = {k.lower(): v for k, v in headers.items()}
```

means that anyone previously relying on upper/title cased header names will now be broken.  Given the preview status of this project, this is still ok, but I wonder if it makes more sense to just have a case insensitive dictionary used for headers instead.

Thoughts?

**Comment by hadrien** [comment]
@jamesls Totally agree, I was being lazy in the first place. 

Please give me feedback on my last commit. 

When/If PR is approved, should I squash commits to make a cleaner history?

**Comment by jamesls** [comment]
No need to squash, I'll go ahead and merge.  Thanks for updating.

**Comment by jamesls** [comment]
Quick update, I had to make a couple of small changes to this.  I want to preserve the property that `app.current_request.to_dict()` will always return JSON serializable data so I made a small update to the `to_dict()` method.

I wasn't able to `dict(request['headers'])` so I updated the code to subclass from `collections.Mapping` to make this possible.  Otherwise everything else is unchanged.

I also added a few tests to catch this in the future (the fact that `to_dict()` is json serializable).

**Comment by jamesls** [comment]
Rebased/merged in https://github.com/awslabs/chalice/commit/d69a2481a918f01a3926ea224e42f6e9f02faf6b

**Pull request closed without merging**
